name: pandoc runner
on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "foo" > input.txt  # create an example file
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --output=formulas.pdf
            formulas.md

